config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  scope "(:locale)", locale: /en|ru|ua|uz|ir|tr|es|de|in/ do
    # Defines the root path route ("/")
    root "webhook#home"

    get "/home", to: "webhook#home", as: :home
    get "/missions", to: "webhook#missions", as: :missions
    get "/wallet", to: "webhook#wallet", as: :wallet
    get "/friends", to: "webhook#friends", as: :friends
    get "/more", to: "webhook#more", as: :more
    get "/terms", to: "webhook#terms_and_conditions", as: :terms

    get "/boost", to: "webhook#boost", as: :boost
    get "/payment/:price", to: "webhook#awaiting_payment", as: :awaiting_payment
    get "/claim", to: "webhook#claim", as: :claim
    post "/claim/create", to: "webhook#claim_create", as: :claim_create
    post "/contest/create", to: "webhook#contest_create", as: :contest_create
    get "/contact_support", to: "webhook#contact_support", as: :contact_support
    get "/legal_information", to: "webhook#legal_information", as: :legal_information
    get "/friends_list", to: "webhook#friends_list", as: :friends_list
    get "/withdraw", to: "webhook#withdraw", as: :withdraw
    # post "/withdraw/create", to: "webhook#create_withdraw", as: :create_withdraw
    get "/friends_learn_more", to: "webhook#friends_learn_more", as: :friends_learn_more
    get "/add_content_and_earn", to: "webhook#add_content_and_earn", as: :add_content_and_earn
    get "/language", to: "webhook#language", as: :language
    post "/tx/push", to: "webhook#push_native_tx", as: :push_native_tx
    get "/deposit/first", to: "webhook#deposit_first", as: :deposit_first
    get "/privacy", to: "webhook#privacy_policy", as: :privacy_policy
    get "/kyc", to: "webhook#kyc", as: :kyc
    get "/acceptable_use_policy", to: "webhook#acceptable_use_policy", as: :acceptable_use_policy
    get "/gdpr", to: "webhook#gdpr_compliance_statement", as: :gdpr_compliance_statement

    get "/mining/get", to: "webhook#get_mining_amount", as: :get_mining_amount
    post "/mining/push", to: "webhook#push_mining_amount", as: :push_mining_amount
    post "/mining/start", to: "webhook#start_mining", as: :start_mining

    resource :withdraw, only: %i[ new create ]
  end
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController
  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new create_params do |tx|
      tx.user_id = current_user.id
      tx.tx_type = :outgoing
      tx.sender = current_user.ton_address
      tx.status = :success
    end

    if @transaction.valid?(:create_withdraw)
      render turbo_stream: turbo_stream.replace("modal", partial: "webhook/deposit_first")
    else
      render turbo_stream: turbo_stream.replace(
        "withdraw_form",
        partial: "withdraws/form", locals: { transaction: @transaction }
      )
    end
  end

  private

  def create_params
    params.require(:transaction).permit(:assembly, :amount, :receiver)
  end
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/withdraws/_form.html.erb
<%= turbo_frame_tag "withdraw_form" do %>
  <%= simple_form_for transaction, url: withdraw_path, data: { controller: "withdraw", withdraw_ton_value: current_user.ton, withdraw_tonix_value: current_user.tonix, withdraw_fee_value: "0.3" } do |f| %>
    <div class="space-y-2" >
      <span class="block text-center text-sm">
        <%= t("withdraw.min_amount") %> 
        <span data-withdraw-target="minSend">-</span>
        </span>
      <div class="relative">
        <select 
          class="block w-full appearance-none bg-black/20 rounded-xl py-2 px-3 pl-8 border-transparent focus:outline-none focus:ring-transparent"
          data-withdraw-target="select"
          data-action="change->withdraw#selectCurrency"
          name="transaction[assembly]"
        >
          <option class="text-white bg-black/20" value="ton" <% if transaction.assembly == "ton" %>selected<% end %>>
            TON
          </option>
          <option class="text-white bg-black/20" value="tonix" <% if transaction.assembly == "tonix" %>selected<% end %>>
            TONIX
          </option>
        </select>
        <img 
          class="absolute w-5 h-5 top-0 left-2 translate-y-1/2"
          src=""
          data-withdraw-target="icon">
      </div>
      <div class="space-y-1">
        <input 
          class="<%= 'ring-1 ring-red-500' if transaction.errors[:receiver].any? %> text-center text-sm w-full appearance-none bg-black/20 rounded-xl py-2 px-3 border-transparent" 
          type="text" 
          placeholder="<%= t("withdraw.address_placeholder") %>"
          name="transaction[receiver]"
          value="<%= transaction.receiver %>"
        >
        <% if transaction.errors[:receiver].any? %>
          <div class="text-red-500 text-sm">
            <%= transaction.errors[:receiver].first %>
          </div>
        <% end %>
      </div>
      <div class="space-y-1">
        <div class="relative">
          <input 
            class="<%= 'ring-1 ring-red-500' if transaction.errors[:amount].any? %> border-0 text-center text-sm w-full appearance-none bg-black/20 focus:ring-1 focus:ring-indigo-500 rounded-xl py-2 px-3" 
            type="number" 
            placeholder="<%= t("withdraw.amount_placeholder") %>"
            data-withdraw-target="amount"
            data-action="input->withdraw#amountChanged"
            name="transaction[amount]"
            step="any"
            value="<%= transaction.amount %>"
          >
          <span 
            class="absolute block text-sm text-blue-500 cursor-pointer right-1 bottom-1/2 -translate-x-2 translate-y-1/2"
            data-action="click->withdraw#max"
          >
            MAX
          </span>
        </div>
        <% if transaction.errors[:amount].any? %>
          <div class="text-red-500 text-sm">
            <%= transaction.errors[:amount].first %>
          </div>
        <% end %>
      </div>
      <div class="space-y-1">
        <span class="text-white/50 block text-sm text-center"><%= t("withdraw.fee") %> <span data-withdraw-target="fee">0,3</span> TON</span>
        <span class="text-white/50 block text-sm text-center font-bold"><%= t("withdraw.received") %> <span data-withdraw-target="received">0</span> <span data-withdraw-target="currency">TON</span></span>
      </div>
      <%= component "button", text: t("withdraw.send_button") %>
    </div>
  <% end %>
<% end %>

app/views/withdraws/new.html.erb
<%= render ModalComponent.new do %>
  <!-- Modal Content -->
  <div 
    class="text-white text-center space-y-3"
    data-controller="withdraw"
    data-withdraw-ton-value="<%= current_user.ton %>"
    data-withdraw-tonix-value="<%= current_user.tonix %>"
    data-withdraw-fee-value="0.3"
  >
    <div class="flex gap-2 justify-between text-sm">
      <div class="flex items-center space-x-2 p-2 rounded-lg bg-black/20 flex-grow">
        <%= tag.img src: "/toncoin-ton-logo.svg", class: "w-4 h-4" %>
        <span><%= current_user.ton.round(2) %> TON</span>
      </div>
      <div class="flex items-center space-x-2 p-2 rounded-lg bg-black/20 flex-grow">
        <%= tag.img src: "/fan.png", class: "w-4 h-4" %>
        <span><%= current_user.tonix.round %> TONIX</span>
      </div>
    </div>

    <span class="font-bold block"><%= t("withdraw.title") %></span>
    <p class="text-white/50 text-sm"><%= t("withdraw.subtitle") %></p>

      <!-- form -->
      <%= render partial: "form", locals: { transaction: @transaction } %>

      <div class="flex flex-col justify-center space-y-3">
        <%= component "button", text: t("withdraw.not_yet_button"), submit: false, variant: "secondary_button", data: { action: "click->modal#close" } %>
      </div>
    </div>
  </div>
<% end %>