config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  scope "(:locale)", locale: /en|ru|ua|uz|ir|tr|es|de|in/ do
    # Defines the root path route ("/")
    root "webhook#home"

    get "/home", to: "webhook#home", as: :home
    get "/missions", to: "webhook#missions", as: :missions
    get "/wallet", to: "webhook#wallet", as: :wallet
    get "/friends", to: "webhook#friends", as: :friends
    get "/more", to: "webhook#more", as: :more
    get "/terms", to: "webhook#terms_and_conditions", as: :terms

    get "/boost", to: "webhook#boost", as: :boost
    get "/payment/:price", to: "webhook#awaiting_payment", as: :awaiting_payment
    get "/claim", to: "webhook#claim", as: :claim
    post "/claim/create", to: "webhook#claim_create", as: :claim_create
    post "/contest/create", to: "webhook#contest_create", as: :contest_create
    get "/contact_support", to: "webhook#contact_support", as: :contact_support
    get "/legal_information", to: "webhook#legal_information", as: :legal_information
    get "/friends_list", to: "webhook#friends_list", as: :friends_list
    get "/withdraw", to: "webhook#withdraw", as: :withdraw
    # post "/withdraw/create", to: "webhook#create_withdraw", as: :create_withdraw
    get "/friends_learn_more", to: "webhook#friends_learn_more", as: :friends_learn_more
    get "/add_content_and_earn", to: "webhook#add_content_and_earn", as: :add_content_and_earn
    get "/language", to: "webhook#language", as: :language
    post "/tx/push", to: "webhook#push_native_tx", as: :push_native_tx
    get "/deposit/first", to: "webhook#deposit_first", as: :deposit_first
    get "/privacy", to: "webhook#privacy_policy", as: :privacy_policy
    get "/kyc", to: "webhook#kyc", as: :kyc
    get "/acceptable_use_policy", to: "webhook#acceptable_use_policy", as: :acceptable_use_policy
    get "/gdpr", to: "webhook#gdpr_compliance_statement", as: :gdpr_compliance_statement

    get "/mining/get", to: "webhook#get_mining_amount", as: :get_mining_amount
    post "/mining/push", to: "webhook#push_mining_amount", as: :push_mining_amount
    post "/mining/start", to: "webhook#start_mining", as: :start_mining

    resource :withdraw, only: %i[ new create ]
  end
end

app/controllers/webhook_controller.rb
class WebhookController < ApplicationController
  before_action :authorize_user, only: :home

  def home
  end

  def start_mining
    if user_logged_in?
      current_user.update mining_started: Time.zone.now
      redirect_to root_path
    end
  end

  def missions
  end

  def kyc
  end

  def friends
    @invite_link = "https://t.me/tonix_dapp_bot?start=#{current_user_id}"
  end

  def wallet
  end

  def more
    @languages = [
      { code: "en", name: "English" },
      { code: "ru", name: "Русский" },
      { code: "ua", name: "Украiнська" },
      { code: "uz", name: "Uzbek" },
      { code: "ir", name: "فارسی" },
      { code: "tr", name: "Türkçe" },
      { code: "es", name: "Español" },
      { code: "de", name: "Deutsch" },
      { code: "in", name: "Indonesian" }
    ]
  end

  def boost
  end

  def awaiting_payment
    @price = params[:price]&.to_i || 10
    @mining_power = 10 * @price
    @rent_period = 30
    @total_profit = 2.5378 * @price
    @daily_profit = 0.0849 * @price
  end

  def claim
  end

  def contact_support
  end

  def add_content_and_earn
    @rewards = [
      { from: "100", to: "999", delta: "10K" },
      { from: "1K", to: "4.9K", delta: "25K" },
      { from: "5K", to: "9.9K", delta: "50K" },
      { from: "10K", to: "49.9K", delta: "100K" },
      { from: "50K", to: "99.9K", delta: "500K" },
      { from: "100K", to: "499.9K", delta: "1M" },
      { from: "500K", to: "999.9K", delta: "5K" },
      { from: "1M", to: nil, delta: "10M" }
    ]
  end

  def legal_information
  end

  def friends_list
  end

  def language
    @languages = [
      { code: "en", flag: "🇺🇸", name: "English" },
      { code: "ru", flag: "🇷🇺", name: "Русский" },
      { code: "ua", flag: "🇺🇦", name: "Украiнська" },
      { code: "uz", flag: "🇺🇿", name: "Uzbek" },
      { code: "ir", flag: "🇮🇷", name: "فارسی" },
      { code: "tr", flag: "🇹🇷", name: "Türkçe" },
      { code: "es", flag: "🇪🇸", name: "Español" },
      { code: "de", flag: "🇩🇪", name: "Deutsch" },
      { code: "in", flag: "🇮🇩", name: "Indonesian" }

    ]
  end

  def withdraw
  end

  def deposit_first
  end

  def create_withdraw
    assembly = create_withdraw_params[:assembly]
    amount = create_withdraw_params[:amount].to_f
    # address = create_withdraw_params[:address]

    if assembly == "ton" && amount < 0.35 ||
        assembly == "tonix" && amount < 150_000 ||
        current_user.send(assembly) < amount
      flash.now[:alert] = t("errors.withdraw.msg")
      render turbo_stream: turbo_stream.update(
        "toast-frame",
        partial: "webhook/toast",
        locals: { message: flash[:alert], type: :alert }
      )
    else
      render turbo_stream: turbo_stream.replace("modal", partial: "deposit_first")

      # tx = Transaction.new(
      #   user_id: current_user.id,
      #   tx_type: :outgoing,
      #   sender: "your_account",
      #   receiver: address,
      #   assembly: assembly,
      #   amount: amount,
      #   status: :success
      # )

      # if tx.save
      #   flash.now[:notice] = t("notices.withdraw.msg")
      #   render turbo_stream: turbo_stream.update(
      #     "toast-frame",
      #     partial: "webhook/toast",
      #     locals: { message: flash[:notice], type: :success }
      #   )
      # else
      #   flash.now[:alert] = t("errors.withdraw.msg2")
      #   render turbo_stream: turbo_stream.update(
      #     "toast-frame",
      #     partial: "webhook/toast",
      #     locals: { message: flash[:alert], type: :alert }
      #   )
      # end
    end
  end

  def friends_learn_more
  end

  def push_mining_amount
    if user_logged_in? && current_user_mining_started?
      amount = mining_amount_params
      current_amount = current_user.mining
      if amount > current_amount
        current_user.update mining: amount
      end
    end
  end

  def privacy_policy
  end

  def acceptable_use_policy
  end

  def gdpr_compliance_statement
  end

  def get_mining_amount
    render json: { amount: (user_logged_in? ? current_user.mining : 0.0) }
  end

  def push_native_tx
    unless Transaction.where(tx_hash: push_native_tx_params[:tx_hash]).exists?
      transaction = Transaction.new(push_native_tx_params) do |tx|
        tx.user_id = current_user.id
      end

      if transaction.save
        render json: { msg: t("notice.push_native_tx.msg") }
      else
        render json: { msg: t("errors.push_native_tx.msg") }, status: :unprocessable_entity
      end
    end
  end

  def claim_create
    @min_claim_amount = 0.015

    if current_user.mining < @min_claim_amount
      render(
        json: { msg: t("errors.claim.too_small") },
        status: :unprocessable_entity
      )
    else
      current_user.claim
      render(
        json: { msg: t("notices.claim.msg") }
      )
    end
  end

  def terms_and_conditions
  end

  def contest_create
    contest = Contest.new contest_params

    if contest.save
      flash.now[:notice] = t("notices.contest.msg")
      render turbo_stream: turbo_stream.update(
        "toast-frame",
        partial: "webhook/toast",
        locals: { message: flash[:notice], type: :success }
      )
    else
      flash.now[:alert] = t("errors.contest.msg")
      render turbo_stream: turbo_stream.update(
        "toast-frame",
        partial: "webhook/toast",
        locals: { message: flash[:alert], type: :alert }
      )
    end
  end

  private

  def push_native_tx_params
    params.require(:transaction).permit(
        :tx_type,
        :sender,
        :receiver,
        :assembly,
        :amount,
        :status,
        :tx_hash
      )
  end

  def mining_amount_params
    params.require(:amount)
  end

  def create_withdraw_params
    params.require(:withdraw).permit(:assembly, :amount, :address)
  end

  def contest_params
    params.require(:contest).permit(:url).merge(user_id: current_user.id)
  end
end

app/helpers/webhook_helper.rb
module WebhookHelper
  def format_large_number(number)
    number.to_s.reverse.scan(/\d{1,3}/).join(" ").reverse
  end
end

app/views/webhook/_balances.html.erb
<!-- Balance 1 -->
<%= tag.div id: "balances" do %>
  <div class="space-y-3">
    <div class="flex items-center justify-between bg-black/30 rounded-xl p-3">
      <div class="flex items-center space-x-2">
        <!-- Icon -->
        <!--div class="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
          <span class="text-lg font-bold">V</span>
        </div-->
        <img src="/toncoin-ton-logo.svg" alt="ton-icon" class="w-10 h-10">
        <!-- Balance Text -->
        <div>
          <p class="text-sm text-slate-300"><%= t("home.balance") %></p>
          <p class="text-sm font-bold text-slate-200"><%= user.ton %> TON</p>
        </div>
      </div>
      <div>
        <%= component "icon_button", url: new_withdraw_path, fa: "fa-solid fa-wallet", data: { turbo_frame: "modal" } %>
      </div>
    </div>

    <!-- Balance 2 -->
    <div class="flex items-center justify-between bg-black/30 rounded-lg p-3">
      <div class="flex items-center space-x-2">
        <!-- Icon -->
        <!--div class="w-8 h-8 bg-blue-700 rounded-full flex items-center justify-center">
          <span class="text-lg font-bold">V</span>
        </div-->
        <img src="/fan.png" alt="ton-icon" class="w-10 h-10">
        <!-- Balance Text -->
        <div>
          <p class="text-sm text-gray-300"><%= t("home.balance") %></p>
          <p class="text-sm font-bold text-slate-200"><%= user.tonix %> TONIX</p>
        </div>
      </div>
      <div>
        <%= component "icon_button", url: new_withdraw_path, fa: "fa-solid fa-wallet", data: { turbo_frame: "modal" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/webhook/_toast.html.erb
<div 
  class="fixed flex items-center space-x-2 top-4 left-1/2 transform -translate-x-1/2 bg-slate-900 text-white p-3 rounded-xl shadow-lg animate-fade"
  data-controller="toast" 
  data-action="animationend->toast#hide"
>
  <% if type == :alert %>
    <i class="fa-solid fa-circle-exclamation text-red-500 block"></i>
  <% elsif type == :success %>
    <i class="fa-solid fa-circle-check text-green-500 block"></i>
  <% end %>
  <span class="text-sm"><%= message %></span>
</div>

app/views/webhook/acceptable_use_policy.html.erb
<%= turbo_frame_tag "modal" do %>
  <div 
    class="fixed inset-0 h-screen w-full bg-slate-800 text-xs text-white/50 p-6 space-y-4 text-start z-50 overflow-y-auto" 
    data-controller="modal" 
    data-modal-target="overlay"
    data-action="click->modal#closeBg"
  >

    <!-- <--<< Back -->
    <div class="flex justify-end w-full">
      <button class="px-4 py-2 flex items-center space-x-2 bg-black/20 text-white/70 rounded hover:bg-gray-300 font-semibold" data-action="click->modal#close">
        <i class="fa-solid fa-arrow-left-long"></i>
        <span>Back</span>
      </button>
    </div>

    <div class="max-w-4xl mx-auto p-6 rounded-lg shadow-md mt-10 leading-relaxed">
      <h1 class="text-2xl font-bold mb-4 text-gray-50">Acceptable Use Policy</h1>
      <p class="text-sm text-gray-300 mb-6">Last updated: 07/04/2024</p>

      <p class="mb-4">
        This Acceptable Use Policy ("Policy") outlines the rules and standards for using the 
        <span class="font-semibold">TONIX.PRO services ("Service")</span>. By accessing or using our Service, you agree to comply with this Policy.
      </p>

      <h2 class="text-xl font-semibold mt-6 mb-4 text-gray-100">1. Prohibited Activities</h2>
      <p class="mb-4">Users are prohibited from using the Service to engage in any of the following activities:</p>
      <ul class="list-disc pl-6 space-y-2">
        <li><span class="font-semibold">Illegal Activities:</span> Any activities that are unlawful, harmful, or fraudulent, including but not limited to committing or encouraging acts of violence, harassment, or discrimination.</li>
        <li><span class="font-semibold">Security Violations:</span> Attempting to interfere with, disrupt, or gain unauthorized access to any systems, networks, or data associated with the Service, including hacking, phishing, or deploying malware.</li>
        <li><span class="font-semibold">Spamming and Phishing:</span> Sending unsolicited messages (spam) or attempting to mislead others into disclosing sensitive information through deceptive tactics (phishing).</li>
        <li><span class="font-semibold">Intellectual Property Infringement:</span> Uploading, sharing, or distributing content that violates the intellectual property rights of others, including copyrights, trademarks, and patents.</li>
        <li><span class="font-semibold">Harmful Content:</span> Distributing or transmitting content that is obscene, offensive, defamatory, or otherwise objectionable, including but not limited to hate speech and graphic violence.</li>
        <li><span class="font-semibold">Automated Use:</span> Using bots, scripts, or other automated methods to interact with the Service in a manner that is not expressly authorized.</li>
      </ul>

      <h2 class="text-xl font-semibold mt-6 mb-4 text-gray-100">2. User Responsibilities</h2>
      <ul class="list-disc pl-6 space-y-2">
        <li><span class="font-semibold">Compliance:</span> Users must comply with all applicable local, state, national, and international laws and regulations when using the Service.</li>
        <li><span class="font-semibold">Reporting Violations:</span> Users are encouraged to report any violations of this Policy to TONIX. We may investigate and take appropriate action, including suspending or terminating accounts, as necessary.</li>
      </ul>

      <h2 class="text-xl font-semibold mt-6 mb-4 text-gray-100">3. Consequences of Violations</h2>
      <ul class="list-disc pl-6 space-y-2">
        <li><span class="font-semibold">Account Suspension or Termination:</span> Violations of this Policy may result in the suspension or termination of the user’s account without notice.</li>
        <li><span class="font-semibold">Legal Action:</span> Depending on the severity of the violation, we may take legal action to enforce compliance with this Policy and seek damages as necessary.</li>
      </ul>

      <h2 class="text-xl font-semibold mt-6 mb-4 text-gray-100">4. Policy Changes</h2>
      <p class="mb-4">
        TONIX reserves the right to modify this Policy at any time. Changes will be effective immediately upon posting. 
        Continued use of the Service after any changes constitutes acceptance of the new terms.
      </p>
    </div>

  </div>
<% end %>

app/views/webhook/add_content_and_earn.html.erb
<%= turbo_frame_tag "modal" do %>
  <div 
    class="fixed inset-0 bg-black bg-opacity-50 backdrop-blur-sm flex items-center justify-center z-50" 
    data-controller="modal" 
    data-modal-target="overlay"
    data-action="click->modal#closeBg"
  >
    <!-- Modal Content -->
    <div class="bg-slate-800 rounded-lg text-sm p-6 w-96 shadow-lg text-white text-start space-y-3">
      <span class="font-bold block"><%= t("add_content_and_earn.title") %></span>
      <span class="block"><%= t("add_content_and_earn.subtitle") %></span>

      <%= form_with model: Contest, url: contest_create_path, method: :post, class: "space-y-3" do |f| %>
        <input class="rounded-xl bg-black/20 w-full" type="text" name="contest[url]">
        
        <!-- separator -->
        <div class="border-b w-full border-white/20"></div>

        <span class="block"><%= t("add_content_and_earn.rewards") %></span>
        <div class="">
          <% @rewards.each do |desc| %>
            <% if desc[:to].present? %>
              <p class="text-xs">
                <%= desc[:from] %> - <%= desc[:to] %> <%= t("add_content_and_earn.views") %> = 
                <img class="w-4 h-4 inline" src="/fan.png" alt=""> 
                <span class="text-amber-400">+ <%= desc[:delta] %></span>
              </p>
            <% else %>
              <p class="text-xs"><%= desc[:from] %>+ <%= t("add_content_and_earn.views") %> = 
                <img class="w-4 h-4 inline" src="/fan.png" alt=""> 
                <span class="text-amber-400">+ <%= desc[:delta] %></span>
              </p>
            <% end %>
          <% end %>
        </div>

        <span class="block"><%= t("add_content_and_earn.views_number") %></span>
        <select id="icon-select" class="block w-full appearance-none bg-black/20 rounded-xl py-2 px-3 border-transparent focus:outline-none focus:ring-transparent">
          <% @rewards.each do |desc, index| %>
          <option class="text-white bg-black/20" value="<%= index %>"<% if index == 0 %> selected<% end %>>
            <span>
              <% if desc[:to].present? %>
                <%= desc[:from] %> - <%= desc[:to] %>
              <% else %>
                <%= desc[:from] %>+
              <% end %>
            </span>
          </option>
          <% end %>
        </select>

        <!--div class="flex space-x-2">
          <input class="rounded" type="checkbox" name="" id="">
          <span class="text=xs text-white/50">I understand that if I provide incorrect data, i will lose access to this functionality</span>
        </div-->

        <div class="flex flex-col justify-center space-y-3">
          <%= f.submit t("add_content_and_earn.add_button"), class: "px-4 py-2 text-center block bg-amber-400 text-black rounded hover:bg-blue-700 font-semibold", data: { action: "click->modal#close", turbo_method: "post" } %>
          <div class="px-4 py-2 block bg-black/20 text-white/70 rounded hover:bg-gray-300 font-semibold text-center" data-action="click->modal#close"><%= t("add_content_and_earn.back_button") %></div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/webhook/claim.html.erb
<%= turbo_frame_tag "modal" do %>
  <div 
    class="fixed inset-0 bg-black bg-opacity-50 backdrop-blur-sm flex items-center justify-center z-50" 
    data-controller="modal" 
    data-modal-target="overlay"
    data-action="click->modal#closeBg"
  >
    <!-- Modal Content -->
    <div class="bg-slate-800 rounded-lg p-6 w-96 shadow-lg text-white text-center space-y-3">
      <span class="font-bold mb-4"><%= t("claim.title") %></span>
      <p class="text-white/70 mb-6 text-sm">
        <%= t("claim.subtitle") %>
      </p>
      <span class="font-bold mb-4"><%= t("claim.min_amount") %> 0.015 TON</span>
      <div class="flex flex-col justify-center space-y-3">
        <%= tag.div t("claim.claim_button"), id: "claim-button", class: "px-4 py-2 block bg-amber-400 text-black font-semibold rounded hover:bg-blue-700", data: { action: "click->modal#close" } %>
        <button class="px-4 py-2 block bg-black/20 text-white/70 rounded hover:bg-gray-300 font-semibold" data-action="click->modal#close"><%= t("claim.back_button") %></button>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    document.querySelector("#claim-button").addEventListener("click", function() {
      const fanController = Stimulus.getControllerForElementAndIdentifier(document.querySelector('[data-controller="fan"]'), "fan")
      
      if (fanController) {
        fanController.claim()
      }
  })
  </script>
<% end %>

app/views/webhook/deposit_first.html.erb
<%= render partial: "deposit_first" %>

app/views/webhook/friends.html.erb
<div class="text-white mt-4 w-full px-4 space-y-4">

  <!-- welcome text -->
  <div class="space-y-1">
    <span class="block w-full text-center font-bold text-xl"><%= t("friends.title") %></span>
    <span class="block w-full text-center"><%= t("friends.subtitle") %></span>
  </div>

  <!-- links and other invite stuff -->
  <div class="p-4 rounded-xl bg-black/20 space-y-2">
    <span class="block w-full font-bold"><%= t("friends.your_invite_link") %></span>
    <button 
      class="bg-white/10 rounded-xl p-3 w-full flex justify-between items-center"
      data-controller="clipboard"
      data-clipboard-content-value="<%= @invite_link %>"
      data-action="click->clipboard#copy"
    >
      <span class="text-white/50"><%= truncate(@invite_link) %></span>
      <i class="fa-solid fa-copy"></i>
    </button>
    <div class="flex space-x-2">
      <a href="tg://msg_url?url=<%= @invite_link %>" class="flex-grow flex items-center justify-center space-x-2 rounded-xl bg-amber-400 font-semibold text-black p-3">
        <i class="fa-solid fa-user-plus"></i>
        <span><%= t("friends.invite_friend_button") %></span>
      </a>
      <button 
        class="rounded-xl bg-amber-400 text-black p-3 w-12"
        data-controller="clipboard"
        data-clipboard-content-value="<%= @invite_link %>"
        data-action="click->clipboard#copy"
      >
        <i class="fa-solid fa-copy"></i>
      </button>
    </div>
  </div>

  <!-- Friends list -->
  <%= link_to friends_list_path, class: "flex-grow flex items-center justify-center space-x-2 rounded-xl bg-amber-400 font-semibold text-black p-3 w-full", data: { turbo_frame: "modal" } do %>
    <i class="fa-solid fa-list"></i>
    <span><%= t("friends.friends_list_button") %></span>
  <% end %>

  <!-- Referral rewards -->

  <% 
    rewards = [
      {
        level: 1,
        tonix: 100,
        mh: 30
      },
      {
        level: 2,
        tonix: 50,
        mh: 15
      },
      {
        level: 3,
        tonix: 15,
        mh: 1
      },
    ]
  %>

  <div class="p-4 rounded-xl bg-black/20 space-y-2">
    <span class="block w-full font-bold"><%= t("friends.referral_rewards") %></span>
    <% 3.times do |i| %>
    <div class="p-3 rounded-xl bg-white/10 flex items-center space-x-4">
      <div class="flex-none space-y-1 flex flex-col items-center">
        <span class="text-xs text-white/50">Level</span>
        <span class="font-bold text-xl"><%= rewards[i][:level] %></span>
      </div>

      <div class="flex-grow justify-center space-x-2 py-1 px-4 rounded-xl bg-black/20 flex">
        <div class="space-y-1 flex flex-col items-center">
          <span class="text-sm font-bold text-amber-400"><%= rewards[i][:tonix] %></span>
          <span class="font-bold text-xs"><%= "TONIX" %></span>
        </div>
        <img class="w-10 h-10" src="/fan.png">
      </div>

      <div class="flex-grow justify-center items-center space-x-2 py-1 px-4 rounded-xl bg-black/20 flex">
        <div class="space-y-1 flex flex-col items-center">
          <span class="text-sm font-bold text-amber-400"><%= rewards[i][:mh] %></span>
          <span class="font-bold text-xs"><%= "MH/s" %></span>
        </div>
        <%= tag.img src: "/bolt.gif", class: "w-8 h-8" %>
      </div>
    </div>
    <% end %>
    <%= link_to t("friends.learn_more"), friends_learn_more_path, class: "flex items-center justify-center w-full space-x-2 rounded-xl bg-amber-400 font-semibold text-black p-3", data: { turbo_frame: "modal" } %>
  </div>
</div>

app/views/webhook/home.html.erb
<!-- Top Balances -->
<div class="space-y-3 w-full overflow-hidden">
  <div class="w-full space-y-4 px-4 py-4">

    <%= turbo_stream_from "user_#{current_user.id}" %>
    <%= render partial: "webhook/balances", locals: { user: current_user } %>

  </div>

  <div 
    class="w-full space-y-2 overflow-hidden"
    data-controller="fan" 
    data-fan-mining-started-value="<%= current_user_mining_started? %>"
    data-fan-gh-amount-value="<%= current_user.gh %>"
  >
    <!-- Circle with Image -->
    <div class="rounded-full overflow-hidden flex items-center justify-center mx-auto relative" style="overflow: visible; width: 260px; height: 260px;" data-fan-target="fan" data-action="click->fan#fanClicked">
      <!-- div src="/fan.png" alt="Fan Icon" class="w-64 h-64 rounded-full inset-0 bg-[url('/fan.png')] bg-cover" data-fan-target="fan"></div -->
      <!-- div class="absolute z-100 bg-[length:300px_300px] bg-center bg-[url('fan.png')] rounded-full w-16 h-16"></div -->
      <div class="user-select-none absolute top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2">
        <img class="h-auto max-w-[260px] user-select-none animate-[spin_4s_linear_infinite]" src="/image.png" draggable="false" alt="Spinner">
      </div>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="13.84 15.63 28.31 28.31" class="w-9 h-9 text-white absolute inset-0 m-auto top-1 mix-blend-overlay"><path d="M37.56 15.628H18.44c-3.516 0-5.745 3.792-3.976 6.858l11.801 20.455c.77 1.335 2.7 1.335 3.47 0l11.804-20.455c1.767-3.06-.462-6.858-3.975-6.858h-.003zM26.255 36.807l-2.57-4.974-6.202-11.092c-.409-.71.096-1.62.953-1.62h7.816V36.81l.003-.002zM38.51 20.739l-6.2 11.096-2.57 4.972V19.119h7.817c.857 0 1.362.91.953 1.62z" fill="#fff"></path></svg>
    </div>

    <!-- Balance with Speed -->
    <div class="text-center mb-4">
      <p class="text-2xl font-semibold text-gray-100">
        <span class="font-roboto-mono" data-fan-target="average">0.0000000000</span>
        <span class="text-amber-300 text-center">TON</span>
      </p>
      <p class="text-gray-400 text-sm">⚙️ <%= current_user.gh %> GH/s ⚡</p>
    </div>
  </div>

  <!-- Action Buttons -->
  <div class="flex space-x-4 w-full px-4">
    <% if current_user_mining_started? %>
      <%= component "icon_button", url: claim_path, text: t("home.claim"), fa: "fa-solid fa-coins", data: { turbo_frame: "modal" } %>
      <%= component "icon_button", url: boost_path, text: t("home.boost"), fa: "fa-solid fa-circle-up", data: { turbo_frame: "modal" } %>
    <% else %>
      <%= component "icon_button", url: start_mining_path, text: t("home.start_mining"), fa: "fa-solid fa-circle-up", data: { turbo_method: :post } %>
    <% end %>
  </div>
</div>

app/views/webhook/language.html.erb
<%= turbo_frame_tag "modal" do %>
  <div 
    class="fixed text-white inset-0 bg-slate-800 flex items-center z-50" 
    data-controller="modal" 
    data-modal-target="overlay"
    data-action="click->modal#closeBg"
  >
    <div class="mx-auto px-24 space-y-2 bg-black/50 rounded-xl p-3">
      <% @languages.each do |language| %>
        <%= link_to more_path(locale: language[:code]), class: "block", data: { action: "click->modal#close", turbo: false } do %>
          <p class="underline text-start font-emoji"><%= language[:flag] %> <%= language[:name] %></p>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>