config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  scope "(:locale)", locale: /en|ru|ua|uz|ir|tr|es|de|in/ do
    # Defines the root path route ("/")
    root "webhook#home"

    get "/home", to: "webhook#home", as: :home
    get "/missions", to: "webhook#missions", as: :missions
    get "/wallet", to: "webhook#wallet", as: :wallet
    get "/friends", to: "webhook#friends", as: :friends
    get "/more", to: "webhook#more", as: :more
    get "/terms", to: "webhook#terms_and_conditions", as: :terms

    get "/boost", to: "webhook#boost", as: :boost
    get "/payment/:price", to: "webhook#awaiting_payment", as: :awaiting_payment
    get "/claim", to: "webhook#claim", as: :claim
    post "/claim/create", to: "webhook#claim_create", as: :claim_create
    post "/contest/create", to: "webhook#contest_create", as: :contest_create
    get "/contact_support", to: "webhook#contact_support", as: :contact_support
    get "/legal_information", to: "webhook#legal_information", as: :legal_information
    get "/friends_list", to: "webhook#friends_list", as: :friends_list
    get "/withdraw", to: "webhook#withdraw", as: :withdraw
    # post "/withdraw/create", to: "webhook#create_withdraw", as: :create_withdraw
    get "/friends_learn_more", to: "webhook#friends_learn_more", as: :friends_learn_more
    get "/add_content_and_earn", to: "webhook#add_content_and_earn", as: :add_content_and_earn
    get "/language", to: "webhook#language", as: :language
    post "/tx/push", to: "webhook#push_native_tx", as: :push_native_tx
    get "/deposit/first", to: "webhook#deposit_first", as: :deposit_first
    get "/privacy", to: "webhook#privacy_policy", as: :privacy_policy
    get "/kyc", to: "webhook#kyc", as: :kyc
    get "/acceptable_use_policy", to: "webhook#acceptable_use_policy", as: :acceptable_use_policy
    get "/gdpr", to: "webhook#gdpr_compliance_statement", as: :gdpr_compliance_statement

    get "/mining/get", to: "webhook#get_mining_amount", as: :get_mining_amount
    post "/mining/push", to: "webhook#push_mining_amount", as: :push_mining_amount
    post "/mining/start", to: "webhook#start_mining", as: :start_mining

    resource :withdraw, only: %i[ new create ]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Coinx" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap" rel="stylesheet">
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/db676a09bb.js" crossorigin="anonymous"></script>
  </head>

  <body 
    class="bg-slate-800 min-h-screen w-screen" 
    data-controller="transactions"
    data-transactions-address-value="<%= current_user.ton_address %>"
  >
    <turbo-frame id="toast-frame">
      <!-- Empty by default -->
    </turbo-frame>

      <!-- Main Container -->
    <div class="mb-[96px] w-full flex flex-col items-center justify-start">
      <%= yield %>

      <!-- Bottom Navigation -->
      <div class="fixed bottom-0 w-full px-7 mb-2">
        <div class="flex bg-slate-900 px-3 py-2 rounded-2xl text-white text-base text-center">
          <% class_list = "flex flex-1 flex-col space-y-1 items-center py-2" + (current_page?(wallet_path) ? " text-amber-400 bg-white/5 rounded-xl" : "") %>
          <%= link_to wallet_path, class: class_list do %>
            <i class="fa-solid fa-wallet text-xl"></i>
            <p class="text-xs capitalize"><%= t("main_menu.wallet") %></p>
          <% end %>

          <% class_list = "flex flex-1 flex-col space-y-1 items-center py-2" + (current_page?(friends_path) ? " text-amber-400 bg-white/5 rounded-xl" : "") %>
          <%= link_to friends_path, class: class_list do %>
            <i class="fa-solid fa-user-group text-xl"></i>
            <p class="text-xs capitalize"><%= t("main_menu.friends") %></p>
          <% end %>

          <% class_list = "flex flex-1 flex-col space-y-1 items-center py-2" + ((current_page?(root_path) || current_page?(home_path)) ? " text-amber-400 bg-white/5 rounded-xl" : "") %>
          <%= link_to root_path, class: class_list do %>
            <svg width="20px" height="20px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path fill="none" stroke="currentColor" stroke-width="3" d="M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z M15,12 C19,15 20,19 20,19 M12,23 C18.0751322,23 23,18.0751322 23,12 C23,5.92486775 18.0751322,1 12,1 C5.92486775,1 1,5.92486775 1,12 C1,18.0751322 5.92486775,23 12,23 Z M12,9 C15,4 19,3 19,3 M12,15 C9,19 5,20 5,20 M9,12 C5,9 4,5 4,5"/>
            </svg>
            <p class="text-xs capitalize"><%= t("main_menu.home") %></p>
          <% end %>

          <% class_list = "flex flex-1 flex-col space-y-1 items-center py-2" + (current_page?(missions_path) ? " text-amber-400 bg-white/5 rounded-xl" : "") %>
          <%= link_to missions_path, class: class_list do %>
            <i class="fa-solid fa-bullseye text-xl"></i>
            <p class="text-xs capitalize"><%= t("main_menu.missions") %></p>
          <% end %>
          
          <% class_list = "flex flex-1 flex-col space-y-1 items-center py-2" + (current_page?(more_path) ? " text-amber-400 bg-white/5 rounded-xl" : "") %>
          <%= link_to more_path, class: class_list do %>
            <i class="fa-solid fa-sliders text-xl"></i>
            <p class="text-xs capitalize"><%= t("main_menu.more") %></p>
          <% end %>
        </div> 
      </div>
    </div>

  <%= turbo_frame_tag "modal" %>

  <div 
    data-controller="client-toast" 
    class="fixed hidden z-[55] items-center space-x-2 top-4 left-1/2 transform -translate-x-1/2 bg-slate-900 text-white p-3 rounded-xl shadow-lg opacity-0 transition-opacity duration-300"
  >
    <i data-client-toast-target="icon" class="fa-solid block"></i>
    <span data-client-toast-target="message" class="text-sm"></span>
  </div>

  </body>
</html>